server:
  port: 8081
  ssl:
    enabled: true
    key-store: "classpath:server.p12"
    key-store-password: 123456
    key-store-type: PKCS12
    client-auth: need
    enabled-protocols: TLSv1.2

    trust-store: "classpath:server.p12"
    trust-store-type: pkcs12
    trust-store-password: 123456

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    properties:
      hibernate:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
